num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
print('sum is', num1+num2)
print('subtraction is ', num1-num2)
print('multiplication is', num1*num2)
print('division is', num1/num2)